export  { buyCake } from './cake/cakeAction'
export { buyIceCream } from './iceCream/iceCreamAction'
export * from './user/userActions'
export { buyChocolate } from './chocolate/chocolateActions'
export { storeMoney } from './counter/counterActions'